
DEFINE VARIABLE varName AS INT64 NO-UNDO.
DEFINE VARIABLE varName AS CHARACTER NO-UNDO.
DEFINE VARIABLE  AS DATE NO-UNDO.

FOR EACH bufferName WHERE TRUE NO-LOCK:
    
END. /* FOR EACH bufferName */

FOR EACH bufferName WHERE TRUE NO-LOCK:
    
END. /* FOR EACH bufferNa
